// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_rint_reg_multi_y_cpp
Rcpp::List fast_rint_reg_multi_y_cpp(const arma::mat& Y, const arma::mat& X, const arma::uvec& group_offsets, const arma::uvec& group_sizes, double gamma_max, double tol, int max_iter, int grid_size);
RcppExport SEXP _VertexWiseR_fast_rint_reg_multi_y_cpp(SEXP YSEXP, SEXP XSEXP, SEXP group_offsetsSEXP, SEXP group_sizesSEXP, SEXP gamma_maxSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP grid_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group_offsets(group_offsetsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group_sizes(group_sizesSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_max(gamma_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type grid_size(grid_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rint_reg_multi_y_cpp(Y, X, group_offsets, group_sizes, gamma_max, tol, max_iter, grid_size));
    return rcpp_result_gen;
END_RCPP
}
// TFCE_cpp_impl
NumericVector TFCE_cpp_impl(NumericVector data, int tail, IntegerMatrix edgelist);
RcppExport SEXP _VertexWiseR_TFCE_cpp_impl(SEXP dataSEXP, SEXP tailSEXP, SEXP edgelistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type tail(tailSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type edgelist(edgelistSEXP);
    rcpp_result_gen = Rcpp::wrap(TFCE_cpp_impl(data, tail, edgelist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VertexWiseR_fast_rint_reg_multi_y_cpp", (DL_FUNC) &_VertexWiseR_fast_rint_reg_multi_y_cpp, 8},
    {"_VertexWiseR_TFCE_cpp_impl", (DL_FUNC) &_VertexWiseR_TFCE_cpp_impl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_VertexWiseR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
