# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_multi_t_cpp <- function(X, Y, block_size = 2048L, tol = 1e-12, return_coefficients = FALSE) {
    .Call(`_VertexWiseR_lm_multi_t_cpp`, X, Y, block_size, tol, return_coefficients)
}

fast_rint_reg_multi_y_cpp <- function(Y, X, group_offsets, group_sizes, gamma_max = 1e8, tol = 1e-8, max_iter = 200L, grid_size = 41L) {
    .Call(`_VertexWiseR_fast_rint_reg_multi_y_cpp`, Y, X, group_offsets, group_sizes, gamma_max, tol, max_iter, grid_size)
}

TFCE_cpp_impl <- function(data, tail, edgelist) {
    .Call(`_VertexWiseR_TFCE_cpp_impl`, data, tail, edgelist)
}

